version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Kolkata"
    target-branch: "dev"
    reviewers:
      - "Jarmos-san"
    labels:
      - "automerge"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Kolkata"
    target-branch: "dev"
    reviewers:
      - "Jarmos-san"
    labels:
      - "automerge"
