name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - uses: abatilo/actions-poetry@v2.0.0
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - run: |
        poetry --version
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -vvv --cov-report xml:cov.xml --cov=Aurochs tests\

    - name: "Upload Coverage Reports to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
